const path = require('path');
const { ModuleFederationPlugin } = require('webpack').container;

// Superset loads each extension by injecting its remoteEntry.js into the
// host page, then calling container.init(sharedScope) and
// container.get('./index'). That contract REQUIRES a Module Federation
// remote — a plain UMD bundle exposes `window[name]` but lacks the
// `.init` / `.get` container API, which surfaces in the browser as
// `TypeError: Cannot read properties of undefined (reading 'init')`
// during Superset's initializeExtension() call.
//
// The container name must match `moduleFederationName` in the manifest.json
// generated by `superset-extensions bundle` — it is derived from
// publisher + name as camelCase joined by an underscore.
const FEDERATION_NAME = 'myOrg_dashboardChatbot';

module.exports = {
  entry: './src/index.tsx',
  output: {
    path: path.resolve(__dirname, 'dist'),
    // Superset serves extension assets under
    // /api/v1/extensions/<publisher>/<name>/, so publicPath must match so
    // that chunks load from the correct URL at runtime.
    publicPath: 'auto',
    clean: true,
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  plugins: [
    new ModuleFederationPlugin({
      name: FEDERATION_NAME,
      // Hashed filename so cache busting works; manifest.json records the
      // hashed name so Superset loads the right file.
      filename: 'remoteEntry.[contenthash].js',
      exposes: {
        './index': './src/index.tsx',
      },
      shared: {
        react: { singleton: true, requiredVersion: false, import: false },
        'react-dom': { singleton: true, requiredVersion: false, import: false },
      },
    }),
  ],
};
