const path = require('path');
const { ModuleFederationPlugin } = require('webpack').container;

// Superset loads each extension by injecting its remoteEntry.js into the host
// page, then calling container.init(sharedScope) and container.get('./index').
// That contract REQUIRES a Module Federation remote — a plain UMD bundle
// exposes window[name] but lacks the .init / .get container API.
//
// The container name must match `moduleFederationName` in the manifest.json
// generated by `superset-extensions bundle` — derived from publisher + name as
// camelCase joined by an underscore.
const FEDERATION_NAME = 'myOrg_homeShell';

module.exports = {
  entry: './src/index.tsx',
  output: {
    path: path.resolve(__dirname, 'dist'),
    publicPath: 'auto',
    clean: true,
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  plugins: [
    new ModuleFederationPlugin({
      name: FEDERATION_NAME,
      filename: 'remoteEntry.[contenthash].js',
      exposes: {
        './index': './src/index.tsx',
      },
      shared: {
        react: { singleton: true, requiredVersion: false, import: false },
        'react-dom': { singleton: true, requiredVersion: false, import: false },
      },
    }),
  ],
};
