apiVersion: analytics/v1
kind: Chart
metadata:
  key: chart.household.ration_card
  name: Ration Card Type Distribution
spec:
  datasetRef: dataset.household.hh_master
  vizType: pie
  params:
    metric: weighted_count
    groupby:
      - Ration_Card_Type_label
