apiVersion: analytics/v1
kind: Chart
metadata:
  key: chart.household.religion_distribution
  name: Religion Distribution
spec:
  datasetRef: dataset.household.hh_master
  vizType: pie
  params:
    metric: weighted_count
    groupby:
      - Religion_of_HH_Head_label
