apiVersion: analytics/v1
kind: Chart
metadata:
  key: chart.household.social_group
  name: Social Group Distribution
spec:
  datasetRef: dataset.household.hh_master
  vizType: pie
  params:
    metric: weighted_count
    groupby:
      - Social_Group_of_HH_Head_label
