apiVersion: analytics/v1
kind: Chart
metadata:
  key: chart.sales.monthly_revenue
  name: Monthly Revenue
spec:
  datasetRef: dataset.sales.orders
  vizType: echarts_timeseries_bar
  params:
    metrics:
      - sum__revenue
    x_axis: order_date
