apiVersion: analytics/v1
kind: Chart
metadata:
  key: chart.sales.order_count_trend
  name: Order Count Trend
spec:
  datasetRef: dataset.sales.orders
  vizType: echarts_timeseries_line
  params:
    metrics:
      - count
    x_axis: order_date
    groupby: []

